{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP5+LV0ECh18H40TuJci/dl",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/basaaria123/Patient-Record-Validator/blob/main/Patient_Record_Validator.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# Custom Exceptions\n",
        "class InvalidAgeError(Exception): pass\n",
        "class MissingFieldError(Exception): pass\n",
        "class FormatError(Exception): pass\n",
        "class InvalidPhoneError(Exception): pass\n",
        "class InvalidNameError(Exception): pass\n",
        "class DuplicateIDError(Exception): pass\n",
        "\n",
        "\n",
        "# Validate single record\n",
        "def validate_patient(record, seen_ids):\n",
        "    try:\n",
        "        if record == \"INVALID DATA\":\n",
        "            raise FormatError(\"Completely invalid record\")\n",
        "\n",
        "        fields = record.split(\",\")\n",
        "        data = {}\n",
        "\n",
        "        for field in fields:\n",
        "            if \":\" not in field:\n",
        "                raise FormatError(\"Invalid field format\")\n",
        "            key, value = field.split(\":\")\n",
        "            data[key.strip()] = value.strip()\n",
        "\n",
        "        # Required fields\n",
        "        required = [\"ID\", \"Name\", \"Age\", \"Phone\"]\n",
        "        for field in required:\n",
        "            if field not in data:\n",
        "                raise MissingFieldError(f\"Missing {field}\")\n",
        "\n",
        "        # Duplicate ID check\n",
        "        if data[\"ID\"] in seen_ids:\n",
        "            raise DuplicateIDError(\"Duplicate ID found\")\n",
        "        seen_ids.add(data[\"ID\"])\n",
        "\n",
        "        # Name validation\n",
        "        name = data[\"Name\"]\n",
        "        if name == \"\" or not name.replace(\" \", \"\").isalpha():\n",
        "            raise InvalidNameError(\"Invalid Name\")\n",
        "\n",
        "        # Age validation\n",
        "        try:\n",
        "            age = int(data[\"Age\"])\n",
        "            if age < 0 or age > 120:\n",
        "                raise InvalidAgeError(\"Age must be between 0 and 120\")\n",
        "        except:\n",
        "            raise InvalidAgeError(\"Age must be a number\")\n",
        "\n",
        "        # Phone validation\n",
        "        phone = data[\"Phone\"]\n",
        "        if not (phone.isdigit() and len(phone) == 10):\n",
        "            raise InvalidPhoneError(\"Phone must be 10 digits\")\n",
        "\n",
        "        return True, data\n",
        "\n",
        "    except MissingFieldError as e:\n",
        "        return False, (\"Missing Field\", str(e))\n",
        "    except InvalidAgeError as e:\n",
        "        return False, (\"Invalid Age\", str(e))\n",
        "    except InvalidPhoneError as e:\n",
        "        return False, (\"Invalid Phone\", str(e))\n",
        "    except InvalidNameError as e:\n",
        "        return False, (\"Invalid Name\", str(e))\n",
        "    except DuplicateIDError as e:\n",
        "        return False, (\"Duplicate ID\", str(e))\n",
        "    except FormatError as e:\n",
        "        return False, (\"Format Error\", str(e))\n",
        "\n",
        "\n",
        "# Process all records\n",
        "def get_valid_patients(patients):\n",
        "    valid_records = []\n",
        "    invalid_records = []\n",
        "    seen_ids = set()\n",
        "\n",
        "    for record in patients:\n",
        "        is_valid, result = validate_patient(record, seen_ids)\n",
        "\n",
        "        if is_valid:\n",
        "            valid_records.append(result)\n",
        "        else:\n",
        "            error_type, message = result\n",
        "            invalid_records.append({\n",
        "                \"record\": record,\n",
        "                \"type\": error_type,\n",
        "                \"error\": message\n",
        "            })\n",
        "\n",
        "    return valid_records, invalid_records\n",
        "\n",
        "\n",
        "# Graph\n",
        "def plot_results(valid, invalid):\n",
        "    labels = [\"Valid\", \"Invalid\"]\n",
        "    values = [len(valid), len(invalid)]\n",
        "\n",
        "    plt.figure()\n",
        "    plt.bar(labels, values)\n",
        "    plt.title(\"Valid vs Invalid Patient Records\")\n",
        "    plt.xlabel(\"Category\")\n",
        "    plt.ylabel(\"Count\")\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "# ----------- MAIN DATA -----------\n",
        "\n",
        "patients = [\n",
        "    \"ID:401,Name:Arun Kumar,Age:30,Phone:9123456789\",\n",
        "    \"ID:431,Name:Test123,Age:30,Phone:9555555555\",\n",
        "    \"ID:402,Name:Divya,Age:22,Phone:9876543210\",\n",
        "    \"ID:432,Name:Meena,Age:abc,Phone:9876543210\",\n",
        "    \"ID:403,Name:Ravi,Age:45,Phone:9988776655\",\n",
        "    \"ID:433,Name:John,Phone:9876543210\",\n",
        "    \"ID:404,Name:Sneha,Age:28,Phone:9876501234\",\n",
        "    \"ID:434,Name:Sara,Age:30,Phone:12345\",\n",
        "    \"ID:405,Name:Kiran,Age:29,Phone:9234567890\",\n",
        "    \"ID:435,Name:Ali,Age:-5,Phone:9876543210\",\n",
        "\n",
        "    \"ID:406,Name:Meena,Age:40,Phone:9345678901\",\n",
        "    \"ID:436,Name:,Age:40,Phone:9876543210\",\n",
        "    \"ID:407,Name:Ajay,Age:35,Phone:9456789012\",\n",
        "    \"Name:NoID,Age:22,Phone:9876543210\",\n",
        "    \"ID:408,Name:Anu,Age:25,Phone:9567890123\",\n",
        "    \"ID:438,Age:30,Phone:9876543210\",\n",
        "    \"ID:409,Name:Vikas,Age:31,Phone:9678901234\",\n",
        "    \"ID:439,Name:Kavya,Phone:9876543210\",\n",
        "    \"ID:410,Name:Neha,Age:28,Phone:9789012345\",\n",
        "    \"INVALID DATA\",\n",
        "\n",
        "    \"ID:411,Name:Rahul,Age:33,Phone:9890123456\",\n",
        "    \"ID:440,Name:Raj,Age:200,Phone:9012309876\",\n",
        "    \"ID:412,Name:Priya,Age:41,Phone:9901234567\",\n",
        "    \"ID:441,Name:Simran,Age:twenty,Phone:9123409876\",\n",
        "    \"ID:413,Name:Sara,Age:27,Phone:9012345678\",\n",
        "    \"ID:442,Name:Amit,Age:45,Phone:abcd123456\",\n",
        "    \"ID:414,Name:Manoj,Age:50,Phone:9123456701\",\n",
        "    \"ID:443,Name:Bad123,Age:29,Phone:9678909876\",\n",
        "    \"ID:415,Name:Deepa,Age:45,Phone:9234567012\",\n",
        "    \"ID:444,Name:Deepa\",\n",
        "\n",
        "    \"ID:416,Name:Harsha,Age:21,Phone:9345670123\",\n",
        "    \"ID:445,Name:Manoj,Age:,Phone:9678909876\",\n",
        "    \"ID:417,Name:Pooja,Age:26,Phone:9456701234\",\n",
        "    \"ID:446,Name:Test,Age:30\",\n",
        "    \"ID:418,Name:Rajesh,Age:60,Phone:9567012345\",\n",
        "    \"ID:401,Name:Duplicate,Age:30,Phone:9999999999\",\n",
        "    \"ID:419,Name:Amit,Age:45,Phone:9670123456\",\n",
        "    \"RANDOM TEXT\",\n",
        "    \"ID:420,Name:Geeta,Age:29,Phone:9781234567\",\n",
        "    \"INVALID DATA\",\n",
        "\n",
        "    \"ID:421,Name:Leela,Age:38,Phone:9892345678\",\n",
        "    \"ID:422,Name:Sunil,Age:55,Phone:9903456789\",\n",
        "    \"ID:423,Name:Anu,Age:20,Phone:9014567890\",\n",
        "    \"ID:424,Name:Prakash,Age:60,Phone:9125678901\",\n",
        "    \"ID:425,Name:Megha,Age:34,Phone:9236789012\",\n",
        "    \"ID:426,Name:Ravi Kumar,Age:33,Phone:9347890123\",\n",
        "    \"ID:427,Name:Kavya,Age:27,Phone:9458901234\",\n",
        "    \"ID:428,Name:Harish,Age:36,Phone:9569012345\",\n",
        "    \"ID:429,Name:Varun,Age:48,Phone:9670123499\",\n",
        "    \"ID:430,Name:Good Name,Age:52,Phone:9781234999\"\n",
        "]\n",
        "\n",
        "\n",
        "# Run\n",
        "valid, invalid = get_valid_patients(patients)\n",
        "\n",
        "\n",
        "# ----------- FORMATTED OUTPUT -----------\n",
        "\n",
        "print(\"\\n===== VALID RECORDS =====\")\n",
        "print(f\"{'ID':<8}{'Name':<20}{'Age':<6}{'Phone':<12}\")\n",
        "print(\"-\" * 50)\n",
        "\n",
        "for v in valid:\n",
        "    print(f\"{v['ID']:<8}{v['Name']:<20}{v['Age']:<6}{v['Phone']:<12}\")\n",
        "\n",
        "\n",
        "print(\"\\n===== INVALID RECORDS =====\")\n",
        "print(f\"{'Record':<60}{'Error Type':<20}{'Message'}\")\n",
        "print(\"-\" * 110)\n",
        "\n",
        "for i in invalid:\n",
        "    print(f\"{i['record']:<60}{i['type']:<20}{i['error']}\")\n",
        "\n",
        "\n",
        "# ----------- GRAPH -----------\n",
        "\n",
        "plot_results(valid, invalid)"
      ],
      "metadata": {
        "id": "2r-OrhwT6G5e"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}